### ISSUE TITLE
Issues with Kakera Reactions and Troubleshooting Bot Functionality

### ISSUE THREAD

**Issue by Furgoder** [GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2023#1]
1.  The bot seems to have trouble recognizing when it rolls a Kakera. It doesn't appear to detect the Kakera and doesn't attempt to claim it. 
2.  In the `bot.py` file, there is a syntax error in the import statement for the `Vars` module. The line `timeString = ':'+ str(vars.repeatMinute)` caused my bot to malfunction. I had to modify it to `timeString = ':'+ str(Vars.repeatMinute)` for the bot to function correctly.
3. I've noticed that the bot sometimes decides to end the rolling process even when there are remaining rolls. I'm curious about how the bot calculates the number of rolls and determines when to conclude the rolling process. Could you please provide insights into the roll count calculation mechanism or any conditions that might lead to the premature termination of rolling?
![image](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2023/assets/81800846/502484b7-e37a-48b4-908c-a5407dc57517)
![image](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2023/assets/81800846/16228dbd-9466-410f-b022-9726a51f6314)

**Comment by GuilleDiazFentanes** [comment]
> * The bot seems to have trouble recognizing when it rolls a Kakera. It doesn't appear to detect the Kakera and doesn't attempt to claim it.
> * In the `bot.py` file, there is a syntax error in the import statement for the `Vars` module. The line `timeString = ':'+ str(vars.repeatMinute)` caused my bot to malfunction. I had to modify it to `timeString = ':'+ str(Vars.repeatMinute)` for the bot to function correctly.
> * I've noticed that the bot sometimes decides to end the rolling process even when there are remaining rolls. I'm curious about how the bot calculates the number of rolls and determines when to conclude the rolling process. Could you please provide insights into the roll count calculation mechanism or any conditions that might lead to the premature termination of rolling?
>   ![image](https://private-user-images.githubusercontent.com/81800846/292371006-502484b7-e37a-48b4-908c-a5407dc57517.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NTcyMjYsIm5iZiI6MTcwMzU1NjkyNiwicGF0aCI6Ii84MTgwMDg0Ni8yOTIzNzEwMDYtNTAyNDg0YjctZTM3YS00OGI0LTkwOGMtYTU0MDdkYzU3NTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDAyMTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OTQ5YTI5ZWNiZDdiZGU4ZTRlZThjNjIzZTQ5N2VkMDkwOGI1ZDAwMDRjYTVlYWE1YzNmMmI1N2JmZDU0NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UmyTW8k9ZyXmkyO0qwXGez6hetj_NMYf9Mrdqj1QBFk)
>   ![image](https://private-user-images.githubusercontent.com/81800846/292371093-16228dbd-9466-410f-b022-9726a51f6314.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NTcyMjYsIm5iZiI6MTcwMzU1NjkyNiwicGF0aCI6Ii84MTgwMDg0Ni8yOTIzNzEwOTMtMTYyMjhkYmQtOTQ2Ni00MTBmLWIwMjItOTcyNmE1MWY2MzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDAyMTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5OGEzNmJjZWUxNmViZjc1NDc0NWVlOTY0MWM5YTRjNDkxZGQ4NWU1YjliYWEzNjcyNmRhZjY2MWRmNDA2ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o1ch03g6HYMmf8Yq1ZZJ350WuI2Jjz0ag_avPcFs4W0)

Ty for trying it!! I will check all your points and give you an answer as soon as posible ^^

**Comment by GuilleDiazFentanes** [comment]
@Furgoder  It´s all fixed now!! 
Thank you for noticing about the (V)vars. repeatMinute error!
The array of kakeras had the first 'k' in capital letters so the comparation did not give any coincidences, it is now fixed. 
I have changed all the files to upgrade the bot and the console, now you should also notice that it doesnt stop when it has still some rolls to use ( the roll calculation was done by continuing to roll until you get a message with "content")

**Comment by Furgoder** [comment]
> @Furgoder It´s all fixed now!! Thank you for noticing about the (V)vars. repeatMinute error! The array of kakeras had the first 'k' in capital letters so the comparation did not give any coincidences, it is now fixed. I have changed all the files to upgrade the bot and the console, now you should also notice that it doesnt stop when it has still some rolls to use ( the roll calculation was done by continuing to roll until you get a message with "content")

Thank you for the prompt response and the fixes! I appreciate your efforts in addressing the issues.

Syntax Errors in bot.py:
In my previous message about syntax errors in bot.py, I forgot to mention that there is also an error in the first line: import vars. It should be import Vars. After the update, this issue remains unresolved and continues to trigger errors.

Kakera Reacts:
While the fix for Kakera reacts didn't completely resolve the issue, I've noticed an improvement. The bot now recognizes when a character is already claimed, and a Kakera should spawn accordingly. However, the problem persists, and I'm wondering if there might be an issue in my Vars.py. For Kakera, I have set the values as follows: desiredKakeras = ['KakeraP','KakeraY','KakeraO','KakeraR','KakeraW','KakeraL'].

I haven't identified any other issues so far. Your attention to these matters is greatly appreciated.

Thank you once again for your time and assistance.

![image](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2023/assets/81800846/08020d3d-d8be-4dc1-bdc9-10f01f792b82)
![image](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2023/assets/81800846/8af6c9d6-cdae-4a27-8820-f625190182a3)

**Comment by Furgoder** [comment]
I still have a question about the bot's functionality. Does the bot only manage rolls initiated by itself, or is it supposed to monitor and respond to rolls from other users as well?

Additionally, if it is intended to monitor rolls from other users, it seems that the bot is not currently performing this task.

**Comment by GuilleDiazFentanes** [comment]
Also changed!, you are a beast finding those types of errors, im so gratefull.
As I said, the case sesitive array of kakeras must be
['kakeraP','kakeraY','kakeraO','kakeraR','kakeraW','kakeraL'].  k and K are REALLY similar. It took me a lot of time to discover that the error was solved by doing this :  KakeraY -> kakeraY

For the moment, the bot only records and manages its own rolls, it is posible to upgrade it in order to listen to other messages, but im still on it.

**Comment by rahaaatul** [comment]
Are you going to add desired waifus?

By the way, how would you pokeroll if the channel is different?

Also, my cmd is like this: it doesn't show if it's working or not, it's just stuck.

![image](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2023/assets/86149861/6e7494e8-dfd1-463b-8cb9-9073c2a58f87)

Is it supposed to be like this?

**Comment by GuilleDiazFentanes** [comment]
> Are you going to add desired waifus?
> 
> By the way, how would you pokeroll if the channel is different?
> 
> Also, my cmd is like this: it doesn't show if it's working or not, it's just stuck.
> 
> ![image](https://private-user-images.githubusercontent.com/86149861/292916582-6e7494e8-dfd1-463b-8cb9-9073c2a58f87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODI5ODcsIm5iZiI6MTcwMzY4MjY4NywicGF0aCI6Ii84NjE0OTg2MS8yOTI5MTY1ODItNmU3NDk0ZTgtZGZkMS00NjNiLThjYjktOTA3M2MyYTU4Zjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEzMTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZmNlNTllNWM3ODAzYzA5NDE5MTk4Mzk5NzVmZmQ4N2IxNGUxZGIzNzc3M2UzODRkZWFhYmRmZDg1MzdhMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oJQ0-kk7ycfFto35BSqjolqwfyF6MyKjMfnm2eEX-qY)
> 
> Is it supposed to be like this?

Hi!!, the bot pokerolls in the same channel (after all the rolls), or do you mean that you want to pokeroll in a different channel by other reason?

About the console, that is completely normal until you reach the minute "repeatMinute = 'xx' "
In a practical example, if i have the var like this : repeatMinute = '30', the console would be stuck until its 14:30, and then again until 15:30 etc etc, check the minute and if u want to test it put 2-3 minutes more than the actual hour and wait

**Comment by rahaaatul** [comment]
By the way, there's a problem, When the script rolls, it expects a message but if someone else sends a message or the bot sends other message like 'kakera recieved', the script completely ignores the roll message it was expecting. What's the solution for it? @GuilleDiazFentanes

**Comment by rahaaatul** [comment]
> Hi!!, the bot pokerolls in the same channel (after all the rolls), or do you mean that you want to pokeroll in a different channel by other reason?

Yes, we have seperate channels for each. Pokerolls are in different channel.

> About the console, that is completely normal until you reach the minute "repeatMinute = 'xx' " In a practical example, if i have the var like this : repeatMinute = '30', the console would be stuck until its 14:30, and then again until 15:30 etc etc, check the minute and if u want to test it put 2-3 minutes more than the actual hour and wait

Thanks, I've figured that out. I modified it a bit to start when i start the script. No repeats.

> About the desired waifus: Yes! im working in all the advanced features, not just that one!

Well, looking forward to it. Although, I modified the code a bit, and created a wishlist text to match and react:

```
if cardSeries in Vars.desiredSeries or cardName in wishList:
```

By the way, I kinda find it slow. It reacts really slow, shouldn't react as quickly as possible?

**Comment by GuilleDiazFentanes** [comment]
> By the way, there's a problem, When the script rolls, it expects a message but if someone else sends a message or the bot sends other message like 'kakera recieved', the script completely ignores the roll message it was expecting. What's the solution for it? @GuilleDiazFentanes
> 
> Do you know a way to monitor all messages, when it runs?

Did u update to the last version, that shouldnt be happening more! the bot should roll all the times he can , if not i can make another change. Try the new version!!

> Yes, we have seperate channels for each. Pokerolls are in different channel.
With the actual code, im afraid that wont be possible, I can change it in a future though!

> Thanks, I've figured that out. I modified it a bit to start when i start the script. No repeats.

Perfect! Now you can test it better! After u have it all carrectly settled the auto repeat is sooo comfortable


> Well, looking forward to it. Although, I modified the code a bit, and created a wishlist text to match and react:
> 
> ```
> if cardSeries in Vars.desiredSeries or cardName in wishList:
> ```

That is a good, start, but u need to change a bit more code for that, im on it in the advanced version!

> By the way, I kinda find it slow. It reacts really slow, shouldn't it react as quickly as possible?
> 
> Also, it didn't react to any kakera's, I wonder why! Can you check?

Yeah my friend, i mafrais you 100% have the old version, thanks to @Furgoder I could solve all that u are saying, update ALL the files for the problems to be solved!!

**Comment by rahaaatul** [comment]
> Did u update to the last version, that shouldnt be happening more! the bot should roll all the times he can , if not i can make another change. Try the new version!!

I downloaded it the first time yesterday after your latest commit. I'd like to ask for an option to make it roll infinitely but stop when a message like this is given: `the roulette is limited to `

> Perfect! Now you can test it better! After u have it all carrectly settled the auto repeat is sooo comfortable

I'm not confident with the auto repeat yet, because I need to monitor when it rolls, and what it rolls, because it completely ignores the kakera, and rolls, when there are other messages in between.

> That is a good, start, but u need to change a bit more code for that, im on it in the advanced version!
I did add more codes to it. But, yeah waiting for your version.

> Yeah my friend, im afraid you 100% have the old version, thanks to @Furgoder I could solve all that u are saying, update ALL the files for the problems to be solved!! ( you will have to put the data again )

I downloaded it yesterday, 24 hours did not occur yet. So I think I'm on the latest version. I directly downloaded the zip file.

**Comment by GuilleDiazFentanes** [comment]
> I downloaded it for the first time yesterday after your latest commit. I'd like to ask for an option to make it roll infinitely but stop when a message like this is given: `the roulette is limited to `. For now, this is how i'm doing it, but it's not perfect:

That solution is perfect, indeed, for my personal use, its the one I use, but for a common github repository there is a problem, different languages. As this should be a solution for everyone, i cant use english only code reception, so i need to do things like checking content is null or similar.

> I'm not confident with the auto repeat yet, because I need to monitor when it rolls, and what it rolls, because it completely ignores the kakera, and rolls, when there are other messages in between.

Put here in the answer your desiredKakeras array, and your line 26-27 of Function.Py 
        bot.triggerSlashCommand(botID, Vars.channelId, Vars.serverId, data = rollCommand)
        time.sleep(1.8)
to see what time sleep do u have

**Comment by rahaaatul** [comment]
Video Demo:


https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2023/assets/86149861/205a5b54-98d0-457a-b963-570b1bc815ac

**Comment by GuilleDiazFentanes** [comment]
> Maybe you could add a dictionary to match with for different languages.

There are a lot of languages but yes, thats my plan

> By the way, can't we go faster? It seems that I can react faster than this script.

The time.sleep 1.8 it´s quite fast, indeed, discord has teorically a maximum of 2 slashroll commands per 5 seconds, you can put a number inferior than 1.8 but it will have some errors. If you use the "$" command you can do it faster, but u wont have the bonus kakera or wish probability.

> Video Demo:
As I see in the video, the kakera you want to react is a 'kakeraT' and in the example we have in the code that one is not included, the complete list of kakeras is: 	  
      "kakera",	
      "kakeraP",
      "kakeraT",
      "kakeraG",
      "kakeraY",
      "kakeraO",
      "kakeraR",
      "kakeraW",
      "kakeraL"

I also changed the number of messages to make it stop from 2 to 3, so it will be less probable to end rolls while there are still rolls without being used.

**Comment by rahaaatul** [comment]
> The time.sleep 1.8 it´s quite fast, indeed, discord has teorically a maximum of 2 slashroll commands per 5 seconds, you can put a number inferior than 1.8 but it will have some errors. If you use the "$" command you can do it faster, but u wont have the bonus kakera or wish probability.

I don't care if the roll is slow, but the claiming has to be faster. It didn't claim any in the video, otherwise I would have showed you. It reacts quite slow, and that's a big problem. 
> 
> > Video Demo:
> > As I see in the video, the kakera you want to react is a 'kakeraT' and in the example we have in the code that one is not included, the complete list of kakeras is:
> > "kakera",
> > "kakeraP",
> > "kakeraT",
> > "kakeraG",
> > "kakeraY",
> > "kakeraO",
> > "kakeraR",
> > "kakeraW",
> > "kakeraL"
> 

Thanks for providing the full list. I thought the one you provided was the complete one. I'm at the early stage of the game, so I need all the kakera I can get.

> I also changed the number of messages to make it stop from 2 to 3, so it will be less probable to end rolls while there are still rolls without being used.

I did not understand this, can you clarify, please? Thank you.

**Comment by GuilleDiazFentanes** [comment]
> I don't care if the roll is slow, but the claiming has to be faster. It didn't claim any in the video, otherwise I would have showed you. It reacts quite slow, and that's a big problem.

Can I see your desired series list? It may have not claim something because its not in your desiredSeries 
```
if cardSeries in Vars.desiredSeries:
               print('Trying to Claim '+ cardName)
```
The bot isnt even trying to claim because its not printing that, check the array

> I did not understand this, can you clarify, please? Thank you.
The bot needs to get 3 messages like the ones u said (kakera reacted) in order to stop, before it were only 2.

**Comment by rahaaatul** [comment]
> > I don't care if the roll is slow, but the claiming has to be faster. It didn't claim any in the video, otherwise I would have showed you. It reacts quite slow, and that's a big problem.
> 
> Can I see your desired series list? It may have not claim something because its not in your desiredSeries

They were not on my list. True. But I'm not talking about that, I'm talking about how much time it takes to claim. At least 3 seconds. That's enough for someone else to snipe the card.

By the way, can you fix this issue:

```python
Traceback (most recent call last):
  File "C:\File\To\Bot.py", line 14, in <module>
    simpleRoll()
  File "C:\File\To\Function.py", line 52, in simpleRoll
    cardName = (jsonCard[0]['embeds'][0]['author']['name'])
                ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'author'
```

It appears after rolling the new free card from Mudae:
![image](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2023/assets/86149861/328b337f-cdcc-4cef-9f4d-1fb0cd1ffd02)

**Comment by GuilleDiazFentanes** [comment]
> They were not on my list. True. But I'm not talking about that, I'm talking about how much time it takes to claim. At least 3 seconds. That's enough for someone else to snipe the card.

Im afraid it can not be faster, discord offers the message send/reception and pythons treats them , if you dont have time.sleep (i didnt put it) you cant do it faster. A thing u can do is put in mudae a 4 second personal protect claim time.


> By the way, can you fix this issue:

I changed Function.Py to try to handle also those erros, it should work ,also kakera value should appear now

**Comment by Furgoder** [comment]
> Also changed!, you are a beast finding those types of errors, im so gratefull. As I said, the case sesitive array of kakeras must be ['kakeraP','kakeraY','kakeraO','kakeraR','kakeraW','kakeraL']. k and K are REALLY similar. It took me a lot of time to discover that the error was solved by doing this : KakeraY -> kakeraY (I also made the change in the readme and default Vars)
> 
> For the moment, the bot only records and manages its own rolls, it is posible to upgrade it in order to listen to other messages, but im still on it.

I apologize for not noticing the syntax issue with Kakera. After the changes, everything is working now. The functionality I reported for the most part is operational, so we can probably consider this matter resolved.

However, I've observed a non-critical issue: when a character with a double Kakera drops, the bot doesn't seem to react to it. I've attached a screenshot for your reference.
![image](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2023/assets/81800846/a138e0ad-a89b-48a3-a9d2-822904d1d86a)
(Before this roll, was roll with free kakera, bot claimed it)

**Comment by GuilleDiazFentanes** [comment]
> However, I've observed a non-critical issue: when a character with a double Kakera drops, the bot doesn't seem to react to it. I've attached a screenshot for your reference.

yeah, i knew that issue, the button syntax for that case is different fro ma normal one and i didnt stop to investigate, in my opinion it might react to the first kakera maybe, but not the second, i might put it on a future but not in my current plan ( a bit difficult hihi)

**Comment by rahaaatul** [comment]
> Im afraid it can not be faster, discord offers the message send/reception and pythons treats them , if you dont have time.sleep to remove (i didnt put it) you cant do it faster. A thing u can do is put in mudae a 4 second personal protect claim time.

That's a way to do it. Thanks.

> I changed Function.Py to try to handle also those erros, it should work ,also kakera value should appear now

Thank you, for adding the `cardPower`, it was really necessary.

> Consider giving a Star to the repository!! @rahaaatul

Sorry, I was so in the coding. I forgot to do it. By the way, can you open the discussion tab, so we could discuss codes there or to ask questions too? @GuilleDiazFentanes

**Comment by rahaaatul** [comment]
Bro, look at the close call:

![image](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2023/assets/86149861/681178df-b41a-4f0b-8792-98e05dcf10f5)

If I wasn't there, it'd be claimed by someone else, it didn't record `Mikasa Ackerman`, then another one. Because someone was doing bot commands. and it missed two of the cards. You need to do  something about it, please @GuilleDiazFentanes

**Comment by GuilleDiazFentanes** [comment]
> > Im afraid it can not be faster, discord offers the message send/reception and pythons treats them , if you dont have time.sleep to remove (i didnt put it) you cant do it faster. A thing u can do is put in mudae a 4 second personal protect claim time.
> 
> That's a way to do it. Thanks.
> 
> > I changed Function.Py to try to handle also those erros, it should work ,also kakera value should appear now
> 
> Thank you, for adding the `cardPower`, it was really necessary.
> 
> > Consider giving a Star to the repository!! @rahaaatul
> 
> Sorry, I was so in the coding. I forgot to do it. By the way, can you open the discussion tab, so we could discuss codes there or to ask questions too? @GuilleDiazFentanes

Discussions created!

**Comment by GuilleDiazFentanes** [comment]
> If I wasn't there, it'd be claimed by someone else, it didn't record `Mikasa Ackerman`, then another one. Because someone was doing bot commands. and it missed two of the cards. You need to do something about it, please @GuilleDiazFentanes

I will think a form for the bot to do it, but if someone is spamming messages the message management that discord offers won’t be very solid to handle it

**Comment by Tegarcs142** [comment]
> > Also changed!, you are a beast finding those types of errors, im so gratefull. As I said, the case sesitive array of kakeras must be ['kakeraP','kakeraY','kakeraO','kakeraR','kakeraW','kakeraL']. k and K are REALLY similar. It took me a lot of time to discover that the error was solved by doing this : KakeraY -> kakeraY (I also made the change in the readme and default Vars)
> > For the moment, the bot only records and manages its own rolls, it is posible to upgrade it in order to listen to other messages, but im still on it.
> 
> I apologize for not noticing the syntax issue with Kakera. After the changes, everything is working now. The functionality I reported for the most part is operational, so we can probably consider this matter resolved.
> 
> However, I've observed a non-critical issue: when a character with a double Kakera drops, the bot doesn't seem to react to it. I've attached a screenshot for your reference. ![image](https://private-user-images.githubusercontent.com/81800846/293135758-a138e0ad-a89b-48a3-a9d2-822904d1d86a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NzY4OTAsIm5iZiI6MTcxODk3NjU5MCwicGF0aCI6Ii84MTgwMDg0Ni8yOTMxMzU3NTgtYTEzOGUwYWQtYTg5Yi00OGEzLWE5ZDItODIyOTA0ZDFkODZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEzMjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MGJkYjgwN2NiMWQ3ZWZkOGYxMDhiNzBjY2UxMmQ0NTdmNTQ3YjIyM2YzNDg5MGE3MDA4YzQwMjY1NWM4ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sNtNoJFotaVsqd0gt-cevrzsUHydKLXf31NFxyVHon8) (Before this roll, was roll with free kakera, bot claimed it)

here a code if i not forgot:
{'type': 20, 'channel_id': '1219296474601619577', 'content': '', 'attachments': [], 'embeds': [{'type': 'rich', 'description': 'Owari no Seraph <:sw:1163913219782492220>\n<:chaoskey:690110264166842421> (**1828**) +5% kakera value\n<:chaoskey:690110264166842421> (**1829**) +5% kakera value\nClaims: #238\nLikes: #275\n**138028**<:kakera:469835869059153940>\n*```fix\n😍 😍 😍 😍 AHHHHHH I LOVE IT 😍 😍 😍 😍\n```*', 'color': 16711756, 'author': {'name': 'Shinoa Hiiragi'}, 'image': {'url': 'https://mudae.net/uploads/5839302/b7RQ0h1pXTOoqadJxfEk~uvGcPpG.png', 'proxy_url': 'https://images-ext-1.discordapp.net/external/WFFDbTYDD92OzOLgh8odiBsofnKieKxDYx86yvHaKwc/https/mudae.net/uploads/5839302/b7RQ0h1pXTOoqadJxfEk~uvGcPpG.png', 'width': 225, 'height': 350}, 'footer': {'text': '(🔑1829)  · Belongs to tegarcs142', 'icon_url': 'https://cdn.discordapp.com/avatars/308171056424812544/71fc4c82d768df9b23ff790eab37c5e6.webp', 'proxy_icon_url': 'https://images-ext-1.discordapp.net/external/bpfNqT3n_clcwoK78FbNyW8BFLcHWQvfh8EJ42CgITw/https/cdn.discordapp.com/avatars/308171056424812544/71fc4c82d768df9b23ff790eab37c5e6.webp'}}], 'timestamp': '2024-06-21T13:11:57.312000+00:00', 'edited_timestamp': None, 'flags': 0, 'components': [{'type': 1, 'id': 1, 'components': [{'type': 2, 'id': 2, 'custom_id': '1253698927929200741p1113134416726851594.2', 'style': 2, 'emoji': {'id': '1197130196357234698', 'name': 'yellowmoon'}}, {'type': 2, 'id': 3, 'custom_id': '1253698927929200741p1113134416726851594.2p2', 'style': 2, 'emoji': {'id': '1197130201700773939', 'name': 'purplemoon'}}, {'type': 2, 'id': 4, 'custom_id': '1253698927929200741p1113134416726851594.2p3', 'style': 2, 'emoji': {'id': '1197130196357234698', 'name': 'yellowmoon'}}]}], 'resolved': {'users': {}, 'members': {}, 'channels': {}, 'roles': {}}, 'id': '1253698929162457140', 'author': {'id': '432610292342587392', 'username': 'Mudae', 'avatar': '29cb28fbf65a3958105026ab03abd306', 'discriminator': '0807', 'public_flags': 65536, 'flags': 65536, 'bot': True, 'banner': None, 'accent_color': None, 'global_name': None, 'avatar_decoration_data': None, 'banner_color': None, 'clan': None}, 'mentions': [], 'mention_roles': [], 'pinned': False, 'mention_everyone': False, 'tts': False, 'application_id': '432610292342587392', 'interaction': {'id': '1253698927929200741', 'type': 2, 'name': 'wa', 'user': {'id': '308171056424812544', 'username': 'tegarcs142', 'avatar': '71fc4c82d768df9b23ff790eab37c5e6', 'discriminator': '0', 'public_flags': 0, 'flags': 0, 'banner': None, 'accent_color': None, 'global_name': 'Tegar Nan Fiqri', 'avatar_decoration_data': None, 'banner_color': None, 'clan': None}}, 'webhook_id': '432610292342587392', 'position': 0, 'interaction_metadata': {'id': '1253698927929200741', 'type': 2, 'user_id': '308171056424812544', 'user': {'id': '308171056424812544', 'username': 'tegarcs142', 'avatar': '71fc4c82d768df9b23ff790eab37c5e6', 'discriminator': '0', 'public_flags': 0, 'flags': 0, 'banner': None, 'accent_color': None, 'global_name': 'Tegar Nan Fiqri', 'avatar_decoration_data': None, 'banner_color': None, 'clan': None}, 'authorizing_integration_owners': {'0': '1113134416726851594'}, 'name': 'wa'}}

**Comment by Tegarcs142** [comment]
> > Also changed!, you are a beast finding those types of errors, im so gratefull. As I said, the case sesitive array of kakeras must be ['kakeraP','kakeraY','kakeraO','kakeraR','kakeraW','kakeraL']. k and K are REALLY similar. It took me a lot of time to discover that the error was solved by doing this : KakeraY -> kakeraY (I also made the change in the readme and default Vars)
> > For the moment, the bot only records and manages its own rolls, it is posible to upgrade it in order to listen to other messages, but im still on it.
> 
> I apologize for not noticing the syntax issue with Kakera. After the changes, everything is working now. The functionality I reported for the most part is operational, so we can probably consider this matter resolved.
> 
> However, I've observed a non-critical issue: when a character with a double Kakera drops, the bot doesn't seem to react to it. I've attached a screenshot for your reference. ![image](https://private-user-images.githubusercontent.com/81800846/293135758-a138e0ad-a89b-48a3-a9d2-822904d1d86a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NTkxNTYsIm5iZiI6MTcxOTg1ODg1NiwicGF0aCI6Ii84MTgwMDg0Ni8yOTMxMzU3NTgtYTEzOGUwYWQtYTg5Yi00OGEzLWE5ZDItODIyOTA0ZDFkODZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDE4MzQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMDZjZDU0YTI3M2NiODk4ZmU3NzAzZjBlZThhZjliZTc0NGE2NzU5YmViNTJmNDNjNGJmYmJiYmY1ZTg1YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dJ59hxNt5wwoYlOnTAATEZdMhz-9E98IMjNLIuhmmEU) (Before this roll, was roll with free kakera, bot claimed it)

Looks like i got fix for it
